# Generated by Django 3.2.7 on 2021-09-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210921_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('values', models.JSONField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.location')),
            ],
        ),
    ]
