# Generated by Django 3.2.7 on 2021-09-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=37.774929, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=-122.419418, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.CharField(default=37.774929, max_length=10),
            preserve_default=False,
        ),
    ]
