# Generated by Django 3.2.7 on 2021-09-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210923_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='values',
        ),
        migrations.AddField(
            model_name='parameter',
            name='param_id',
            field=models.CharField(default='temp', max_length=20),
            preserve_default=False,
        ),
    ]
