# Generated by Django 3.2.7 on 2021-09-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210924_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='param_id',
            new_name='api_id',
        ),
    ]
